CREATE TABLE IF NOT EXISTS migraines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    start TIMESTAMP NOT NULL,
    stop TIMESTAMP,
    intensity INTEGER,
    medication TEXT,
    reason TEXT,
    notes TEXT
);
